### ISSUE TITLE
Converting the existing code to be a GUI based program

### ISSUE THREAD

**Issue by steelwolf180** [steelwolf180/Midas#5]
We will need to someone to convert the codes from text based application to a GUI based application.

**Comment by TrollDecker** [comment]
I cobbled together a GUI this morning:
https://github.com/RichieStacker/PersonalFinancialPlan/blob/master/Midas_UI.py

As it is right now, it's non-functioning for now, as I've been focusing on just getting it laid out, with the aim of having a layout to demonstrate and adjust as required. It'll display, of course. It just won't do anything just yet.

The current colours are temporary, just so that I could tell them and their edges apart from the rest of the window. Eventually, they'll be reverted to their defaults.

**Comment by steelwolf180** [comment]
Great then i will hand the GUI creation under your care then. Richie you doing a great job men. I will work towards making our codes to run on windows os without installation of python since it will be useful to do that for those non technical oriented person to use the application.
